package vfcore

const (
	TYPE_FUCTION_BLOCK = iota
	TYPE_FUCTION_BLOCK_LIB
	TYPE_FUCTION_BLOCK_TYPE
	TYPE_FUCTION_BLOCK_IMPL

	TYPE_COMMON_VIEW
	TYPE_GLOBAL_SETTINGS
	TYPE_UNIT_SETTINGS
	TYPE_ALARM_LEVEL
	TYPE_SECURITY_SETTINGS

	TYPE_CONTROL_VIEW
	TYPE_CONTROL_AREA
	TYPE_CONTROL_STATION
	TYPE_COM
	TYPE_CANBUS
	TYPE_IO
	TYPE_CHANNEL

	TYPE_MONITOR_VIEW
	TYPE_OPERATORION_AREA
	TYPE_HOST_NODE
	TYPE_OPERATORION_STATION
	TYPE_TEAM
	TYPE_FLOW_CHART_NODE
	TYPE_FLOW_CHART_IMPL
	TYPE_TAG
	TYPE_TREND_NODE
	TYPE_TREND_IMPL

	TYPE_DOMAIN_NODE
	TYPE_STRING_NODE
	TYPE_STRING_IMPL
	TYPE_ANALOG_NODE
	TYPE_ANALOG_IMPL
	TYPE_SWITCH_NODE
	TYPE_SWITCH_IMPL
	TYPE_CALCULATE_NODE
	TYPE_CALCULATE_IMPL
	TYPE_ALARM_NODE
	TYPE_ALARM_IMPL

	TYPE_PROGRAM_NODE
	TYPE_PROGRAM_IMPL

	TYPE_TAG_NODE
	TYPE_AITAG_NODE
	TYPE_AOTAG_NODE
	TYPE_DITAG_NODE
	TYPE_DOTAG_NODE
	TYPE_NATAG_NODE
	TYPE_NDTAG_NODE
	TYPE_NNTAG_NODE
	TYPE_PATAG_NODE
	TYPE_PDTAG_NODE
	TYPE_PNTAG_NODE

	TYPE_TYPICALLOOP_NODE
	TYPE_TYPICALLOOP_IMPL
	TYPE_TYPICALLOOP_TYPE // 52 典型回路类型

	TYPE_SIS_FUCTION_BLOCK_TYPE // 53 Tricon TCS900功能块类型
	TYPE_SIS_FUCTION_BLOCK_IMPL // 54 Tricon TCS900功能块实例
	TYPE_SIS_HARDWARE           // 55 Tricon TCS900机架列表
	TYPE_SIS_CHASSIS            // 56 Tricon TCS900机架
	TYPE_SIS_BOARD_IMPL         // 57 Tricon TCS900卡件
	// 位号表沿用 39 TYPE_TAG_NODE
	TYPE_SIS_MEMORY_TAG_NODE // 58 Tricon TCS900 Memory位号列表
	TYPE_SIS_MEMORY_TAG_IMPL // 59 Tricon TCS900 Memory位号
	TYPE_SIS_INPUT_TAG_NODE  // 60 Tricon Input位号列表
	TYPE_SIS_INPUT_TAG_IMPL  // 61 Tricon Input位号
	TYPE_SIS_OUTPUT_TAG_NODE // 62 Tricon Output位号列表
	TYPE_SIS_OUTPUT_TAG_IMPL // 63 Tricon Output位号
	// 程序集沿用 37 TYPE_PROGRAM_NODE
	TYPE_SIS_PROGRAM_IMPL       // 64 Tricon TCS900 程序节点
	TYPE_SIS_HARDWARE_TAG_NODE  // 65 TCS900 HARDWARE位号列表
	TYPE_SIS_HARDWARE_TAG_IMPL  // 66 TCS900 HARDWARE位号
	TYPE_SIS_COM_TAG_NODE       // 67 TCS900 COM位号列表
	TYPE_SIS_COM_TAG_IMPL       // 68 TCS900 COM位号
	TYPE_SIS_SYNC_TAG_NODE      // 69 TCS900 SYNC位号列表
	TYPE_SIS_SYNC_TAG_IMPL      // 70 TCS900 SYNC位号
	TYPE_SIS_COMMU_TAG_NODE     // 71 TCS900 Commu位号列表
	TYPE_SIS_COMMU_TAG_IMPL     // 72 TCS900 Commu位号
	TYPE_SIS_ESSTATION_TAG_NODE // 73 TCS900 ESStation位号列表
	TYPE_SIS_ESSTATION_TAG_IMPL // 74 TCS900 ESStation位号
	TYPE_SIS_ESCOMMU_TAG_NODE   // 75 TCS900 ESCommu位号列表
	TYPE_SIS_ESCOMMU_TAG_IMPL   // 76 TCS900 ESCommu位号
)
